steps:

- id: generate-html-from-python-apps
  uses: docker://python:3.8-slim-buster
  runs: [bash, -uexc]
  args:
  - |
    # gets all subdirectories of html-apps
    # each subdirectory should contain a file to generate apps and their
    # requirements (if any)
    for app in $(find html-apps/ -maxdepth 1 -mindepth 1 -type d -printf '%f\n'); do
        if [[ ! -f "html-apps/$app/generate_html.py" ]]; then
          continue
        fi
        cd html-apps/"$app"

        # create and activate virtualenv
        python -m venv __"$app"_venv__
        source __"$app"_venv__/bin/activate

        # install requirements, if any
        if [[ -f "requirements.txt" ]]; then
            pip install --upgrade pip
            pip install -r requirements.txt
        fi

        # run generator file
        python generate_html.py

        deactivate
        cd ../..
    done

    pip install jinja2
    python generate_template.py


- id: start-dashboard
  uses: ./docker/dashboard
  env:
    ADMIN_USER: admin
    ADMIN_PASS: admin
    ADMIN_FIRST: first
    ADMIN_LAST: last
    ADMIN_EMAIL: first.last@my.org
  options:
    ports:
      80/tcp: 8080
