steps:

- id: generate-html-from-python-apps
  uses: docker://python:3.8-slim-buster
  runs: [bash, -uexc]
  args:
  - |
    # gets all subdirectories of app/dashboard
    # each subdirectory should contain a file to generate apps and their
    # requirements (if any)
    repo_dir="${PWD}"
    apps_dir="${repo_dir}/app/dashboard"
    for app in $(find "${apps_dir}/" -maxdepth 1 -mindepth 1 -type d -printf '%f\n'); do
      if [[ ! -f "${apps_dir}/${app}/generate_html.py" ]]; then
        continue
      fi

      mkdir -p "data/${app}"
      cd "${apps_dir}/${app}"

      # create and activate virtualenv
      python -m venv "__${app}_venv__"
      source "__${app}_venv__/bin/activate"

      # install requirements, if any
      if [[ -f "requirements.txt" ]]; then
        pip install --upgrade pip
        pip install -r requirements.txt
      fi

      # run generator file
      cd "${repo_dir}"
      python "${apps_dir}/${app}/generate_html.py"

      deactivate
    done

    pip install jinja2
    pip install pyyaml
    python generate_template.py


- id: start-dashboard
  uses: ./docker/dashboard
  env:
    ADMIN_USER: admin
    ADMIN_PASS: admin
    ADMIN_FIRST: first
    ADMIN_LAST: last
    ADMIN_EMAIL: first.last@my.org
  options:
    ports:
      80/tcp: 8080
